name:                little-logger
version:             0.3.1
github:              "ejconlon/little-logger"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2020 Eric Conlon"
category:            Logging
synopsis:            Basic logging based on co-log

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/ejconlon/little-logger#readme>

dependencies:
- base >= 4.12 && < 5
- co-log >= 0.4 && < 1
- co-log-core >= 0.2 && < 1
- microlens >= 0.4 && < 1
- mtl >= 2.2 && < 3
- text >= 1.2 && < 2
- unliftio-core >= 0.1.2.0 && < 2

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

library:
  source-dirs: src
  exposed-modules:
  - LittleLogger
  - LittleLogger.Manual
  - LittleLogger.Reader

tests:
  little-logger-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - little-logger
    - tasty >= 1.2.3 && < 2
    - tasty-hunit >= 0.10.0.2 && < 1
