name:                little-logger
version:             3.0.0
github:              "ejconlon/little-logger"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2022 Eric Conlon"
category:            Logging
synopsis:            Basic logging based on monad-logger

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/ejconlon/little-logger#readme>

dependencies:
- base >= 4.12 && < 5
- monad-logger >= 0.3 && < 0.4
- mtl >= 2.2 && < 3
- optics >= 0.4 && < 1
- text >= 1.2 && < 2.1
- unliftio-core >= 0.1.2.0 && < 2

default-extensions:
- ConstraintKinds
- DerivingStrategies
- DerivingVia
- GeneralizedNewtypeDeriving

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

library:
  source-dirs: src

tests:
  little-logger-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - little-logger
    - directory >= 1.3.6.0 && < 1.4
    - tasty >= 1.2.3 && < 2
    - tasty-hunit >= 0.10.0.2 && < 1
    - temporary >= 1.3 && < 1.4
